env:
  browser: true
  es2021: true
  jest/globals: true
plugins:
  - jest
extends: 
  - airbn-base
  - plugin:jest/recommended
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - 4
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - double
  semi:
    - error
    - always
  no-console: 0
  import/extensions: 0
  no-awit-in-loop: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
